version: "3"
services:
  postgres:
    image: postgres:11.5
    container_name: rickmorty47_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rickmorty47"
